# Generated by Django 4.0.6 on 2022-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='datestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
