# Generated by Django 4.0.6 on 2022-07-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_alter_contactus_datestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='datestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
