# Generated by Django 4.0.1 on 2022-03-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_calorie_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_step_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_water_intake_goal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
