# Generated by Django 4.0.1 on 2022-03-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_calorie_goal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_step_goal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_water_intake_goal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
