# Generated by Django 4.0.1 on 2022-03-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], max_length=1, null=True),
        ),
    ]
