# Generated by Django 4.0.1 on 2022-05-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_calorie_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_step_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_water_intake_goal',
        ),
    ]
