# Generated by Django 4.0.1 on 2022-06-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_profile_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
