# Generated by Django 4.0.6 on 2022-07-18 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPilotTest',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('datestamp', models.DateField()),
                ('physical_activity_type', models.TextField()),
                ('physical_activity_level', models.TextField()),
                ('physical_activity_active_days', models.TextField()),
                ('physical_activity_active_hours', models.TextField()),
                ('avg_work_week_sitting_hours', models.TextField()),
                ('daily_work_week_sitting_hours', models.TextField()),
                ('daily_tv_hours', models.TextField()),
                ('daily_screen_play_hours', models.TextField()),
                ('daily_screen_hours', models.TextField()),
                ('bed_time', models.TextField()),
                ('fall_asleep_in_minutes', models.TextField()),
                ('wake_up_time', models.TextField()),
                ('daily_sleep_hours', models.TextField()),
                ('overall_sleep_quality', models.TextField()),
                ('nutrition_tracker_usage', models.TextField()),
                ('application_usage', models.TextField()),
                ('likelihood_intervention_usage', models.TextField()),
                ('feature_wish_list', models.TextField()),
                ('rating', models.TextField()),
                ('weight', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
