# Generated by Django 4.0.6 on 2022-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpilottest', '0002_alter_postpilottest_physical_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpilottest',
            name='physical_activity_type',
            field=models.TextField(verbose_name='During the experiment period, what type of physical activities did you perform?'),
        ),
    ]
