# Generated by Django 4.0.6 on 2022-07-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='app',
            field=models.CharField(max_length=20),
        ),
    ]
