# Generated by Django 4.0.6 on 2022-07-25 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignLog',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('datestamp', models.DateTimeField(auto_now=True)),
                ('log_status', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
