# Generated by Django 4.0.6 on 2022-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintake',
            name='datestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='waterintake',
            name='drink_progress',
            field=models.FloatField(),
        ),
    ]
