# Generated by Django 4.0.1 on 2022-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieIntake',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('datestamp', models.DateField(blank=True, null=True)),
                ('consume', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
