# Generated by Django 4.0.1 on 2022-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieCategory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
