# Generated by Django 4.0.1 on 2022-03-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_rename_category_caloriefooddetail_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caloriefooddetail',
            old_name='category_id',
            new_name='category',
        ),
    ]
