# Generated by Django 4.0.1 on 2022-03-24 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0005_rename_category_id_caloriefooddetail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieintake',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calorieintake',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='calories.caloriefooddetail'),
            preserve_default=False,
        ),
    ]
