# Generated by Django 4.0.6 on 2022-07-28 08:07

import calories.models.calorie_food_detail
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0007_calorieintake_calories_calorieintake_carb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorieintake',
            name='food_detail_ref',
            field=models.IntegerField(blank=True, null=True, verbose_name=calories.models.calorie_food_detail.CalorieFoodDetail),
        ),
    ]
