# Generated by Django 4.0.6 on 2022-07-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0008_alter_calorieintake_food_detail_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorieintake',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='carb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='consume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='fiber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='food',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='food_detail_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calories.caloriefooddetail'),
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calorieintake',
            name='sugar',
            field=models.FloatField(),
        ),
    ]
