# Generated by Django 4.0.6 on 2022-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoros', '0005_remove_pomodoro_break_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='datestamp',
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='datetimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
