# Generated by Django 4.0.6 on 2022-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoros', '0006_remove_pomodoro_datestamp_pomodoro_datetimestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='datetimestamp',
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='datestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
