# Generated by Django 4.0.6 on 2022-07-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='haha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
