# Generated by Django 4.0.1 on 2022-05-24 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('water_goal', models.FloatField(blank=True, default=0.0)),
                ('calories_goal', models.FloatField(blank=True, default=0.0)),
                ('step_goal', models.FloatField(blank=True, default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
