# Generated by Django 4.0.1 on 2022-05-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='calories_goal',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='step_goal',
            new_name='steps',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='water_goal',
            new_name='water',
        ),
    ]
