# Generated by Django 4.0.1 on 2022-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xp',
            name='datestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
