# Generated by Django 4.0.1 on 2022-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xps', '0002_xp_datestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xp',
            name='datestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
