# Generated by Django 4.0.1 on 2022-06-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xps', '0003_alter_xp_datestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xp',
            name='datestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
