# Generated by Django 4.0.1 on 2022-03-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True)),
                ('challenge', models.CharField(blank=True, choices=[('NO_CHOCOLATE', 'No chocolate'), ('NO_SMOKING', 'No smoking')], max_length=15)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
