# Generated by Django 4.0.1 on 2022-03-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='author',
        ),
    ]
