# Generated by Django 4.0.1 on 2022-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challenge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge',
            field=models.CharField(blank=True, choices=[('NO_ALCOHOL', 'No alcohol'), ('NO_CHOCOLATE', 'No chocolate'), ('NO_FAST_FOOD', 'No fast food'), ('NO_SMOKING', 'No smoking'), ('NO_SUGAR', 'No sugar')], max_length=15),
        ),
    ]
