# Generated by Django 4.0.1 on 2022-03-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_challenge_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge',
            field=models.CharField(choices=[('NO_ALCOHOL', 'No alcohol'), ('NO_CHOCOLATE', 'No chocolate'), ('NO_FAST_FOOD', 'No fast food'), ('NO_SMOKING', 'No smoking'), ('NO_SUGAR', 'No sugar')], max_length=15),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
