# Generated by Django 4.0.1 on 2022-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_challenge_challenge_alter_challenge_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
